version: 2
jobs:
  build:
    docker:
      - image: docker:git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Create Docker volumes
          command: |
            docker create --name input --volume /home/builder/package alpine:3.9 /bin/true
            docker create --name output --volume /packages alpine:3.9 /bin/true
            docker cp ./APKBUILD input:/home/builder/package/
      - run:
          name: Build packages
          command: |
            docker run --env RSA_PRIVATE_KEY="$RSA_PRIVATE_KEY" --env RSA_PRIVATE_KEY_NAME="sgerrand.rsa" \
                       --volumes-from input --volumes-from output sgerrand/alpine-abuild:3.9
      - run:
          name: Extract packages
          command: |
            mkdir -p packages
            docker cp output:/packages/builder packages/
      - run:
          name: Remove Docker volumes
          command: |
            docker rm input
            docker rm output
          when: always
      - store_artifacts:
          destination: pkgs
          path: packages
      - persist_to_workspace:
          root: .
          paths:
            - packages/builder/x86_64
    working_directory: ~/alpine-pkg-git-crypt
  test:
    docker:
      - image: alpine:3.9
    steps:
      - run:
          name: Install CA certificates
          command: apk add --no-cache ca-certificates
      - attach_workspace:
          at: .
      - run:
          name: Add package signing key
          command: wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://raw.githubusercontent.com/sgerrand/alpine-pkg-git-crypt/master/sgerrand.rsa.pub
      - run:
          name: Test installing packages
          command: apk add --no-progress --no-cache ./packages/builder/x86_64/git-crypt-*.apk
      - run:
          name: Test executable
          command: |
            __now="$(date -u +%s)"
            __wdir="tmp/${__now}/"
            mkdir -p $__wdir
            touch $__wdir/test
            cd $__wdir
            git init
            git-crypt status
    working_directory: ~/alpine-pkg-git-crypt
  release-master:
    docker:
      - image: golang:alpine
    steps:
      - attach_workspace:
          at: .
      - run: apk add --no-cache --no-progress git
      - run: go get github.com/tcnksm/ghr
      - run:
          name: Release packages
          command: |
            ghr -u sgerrand -r $CIRCLE_PROJECT_REPONAME -prerelease -delete unreleased packages
            ghr -u sgerrand -r $CIRCLE_PROJECT_REPONAME -prerelease unreleased packages/builder/x86_64
    working_directory: ~/alpine-pkg-git-crypt
  release-tag:
    docker:
      - image: golang:alpine
    steps:
      - attach_workspace:
          at: .
      - run: apk add --no-cache --no-progress git
      - run: go get github.com/tcnksm/ghr
      - run:
          name: Release packages
          command: |
            ghr -u sgerrand -r $CIRCLE_PROJECT_REPONAME $CIRCLE_TAG packages
            ghr -u sgerrand -r $CIRCLE_PROJECT_REPONAME $CIRCLE_TAG packages/builder/x86_64
    working_directory: ~/alpine-pkg-git-crypt
workflows:
  version: 2
  build-test-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release-master:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
      - release-tag:
          requires:
            - build
            - test
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+){1,2}(\-r\d+)?$/
            branches:
              ignore: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
